<a href="https://colab.research.google.com/github/Shohjahon02/first_my_git/blob/main/2_(8_3).ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import numpy as np

In [ ]:
a = [[1, 2, 3, 4], [5, 6, 7, 8], [9, 10, 11, 12]]
arr4 = np.array(a)

In [ ]:
arr4.shape

(3, 4)

In [ ]:
arr4.ndim

2

In [ ]:
arr4.size

12

In [ ]:
arr5 = np.zeros(shape =(3,3))
arr5

array([[0., 0., 0.],
       [0., 0., 0.],
       [0., 0., 0.]])

In [ ]:
arr6 = np.ones((2,5))
arr6

array([[1., 1., 1., 1., 1.],
       [1., 1., 1., 1., 1.]])

In [ ]:
arr7 = np.arange(2, 21, 2)
arr7

array([ 2,  4,  6,  8, 10, 12, 14, 16, 18, 20])

In [ ]:
arr8 = np.random.rand(3, 3)
arr8

array([[0.97790919, 0.86410483, 0.00250295],
       [0.3164111 , 0.92316324, 0.56810907],
       [0.01252849, 0.66692014, 0.48263604]])

In [ ]:
arr9 = np.random.randint(10, size=(3,3))
arr9

array([[9, 3, 7],
       [6, 0, 3],
       [4, 0, 5]])

In [ ]:
arr10 = np.random.randn(3, 3)
arr10

array([[-0.42186132,  1.02968041, -0.16033793],
       [-0.4610402 , -1.37056407, -0.38903405],
       [-0.49820875,  1.45467115, -0.21411313]])

In [ ]:
def one_dim(n):
  arr = np.random.randint(10, size=(1, n))
  return arr

In [ ]:
one_dim(10)

array([[2, 1, 9, 6, 2, 9, 6, 4, 4, 8]])

In [ ]:
arr = np.arange(10, 100+1, 10)
arr[1:]

array([ 20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
sel_arr = arr[2:5]
sel_arr[:] = 0
sel_arr

array([0, 0, 0])

In [ ]:
arr

array([ 10,  20,   0,   0,   0,  60,  70,  80,  90, 100])

In [ ]:
arr1 = np.arange(10, 100+1, 10)
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
sel1 = arr1[2:6].copy()
sel1

array([30, 40, 50, 60])

In [ ]:
sel1[:] = 0
sel1

array([0, 0, 0, 0])

In [ ]:
arr1

array([ 10,  20,  30,  40,  50,  60,  70,  80,  90, 100])

In [ ]:
arr2 = np.random.randint(10, size=(3, 3))
arr2

array([[5, 4, 7],
       [8, 6, 4],
       [2, 7, 9]])

In [ ]:
arr2[1,1]

6

In [ ]:
arr2[2, 0]

2

In [ ]:
arr2[1, 0:]

array([8, 6, 4])

In [ ]:
arr2[:2, 1:]

array([[4, 7],
       [6, 4]])

In [ ]:
arr3 = np.random.randint(30, size=(9, 3))
arr3

array([[29,  8, 25],
       [17, 13,  4],
       [14, 12,  8],
       [ 8,  5, 24],
       [28, 21, 10],
       [26, 20, 14],
       [ 5, 26, 20],
       [ 4,  2, 21],
       [22,  6, 25]])

In [ ]:
arr3d = np.array([[[ 0,  1,  2],
                   [ 3,  4,  5],
                   [ 6,  7,  8]],

                  [[ 9, 10, 11],
                   [12, 13, 14],
                   [15, 16, 17]],

                  [[18, 19, 20],
                   [21, 22, 23],
                   [24, 25, 26]]])
arr3d

array([[[ 0,  1,  2],
        [ 3,  4,  5],
        [ 6,  7,  8]],

       [[ 9, 10, 11],
        [12, 13, 14],
        [15, 16, 17]],

       [[18, 19, 20],
        [21, 22, 23],
        [24, 25, 26]]])

In [ ]:
arr3d[0][1,2]

5

In [ ]:
arr3d[2][0:1]

array([[18, 19, 20]])

In [ ]:
arr3d[1][2, 1:]

array([16, 17])

In [ ]:
arr3d[2][1, :2]

array([21, 22])

In [ ]:
def nd_array():
  arr = np.arange(0, 9, 1, shape=(3, 3))

In [ ]:
arr = np.arange(0, 9, 1)
arr.shape=(3, 3)
arr

array([[0, 1, 2],
       [3, 4, 5],
       [6, 7, 8]])

In [ ]:
 arr3d = np.array([[[ 0,  1,  2],
                      [ 3,  4,  5],
                      [ 6,  7,  8]],

                    [ [ 9, 10, 11],
                      [12, 13, 14],
                      [15, 16, 17]],

                     [[18, 19, 20],
                      [21, 22, 23],
                      [24, 25, 26]]])
sl_arr = arr3d[1][1:, :2]
sl_arr

array([[12, 13],
       [15, 16]])

# Новый раздел