<a href="https://colab.research.google.com/github/Shohjahon02/first_my_git/blob/main/Copy_of_mohirdev_NumPy.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

# NumPy kutubxonasiga doir bilimlaringizni mustaxkamlash uchun mashqlar

Hurmatli o'quvchi, bilimingizni yanada mustaxkamlashingiz va chuqurroq ko'nikmalarga ega bo'lishingiz uchun sizga topshiriqlar tayyorladik. Sizga yengillik yaratish maqsadida topshiriqni aynan qanday funksiyalar yordamida amalga oshirishingiz mumkin ekanini 
 `💡Ishora` ko'rinishida yozdik!

#### 1. NumPy kutubxonasini `np` nomi ostida yuklang va numpy kutubxonasini chop eting.

versiya va konfiguratsiyani tekshiring.


`💡Ishora` import … as` and `np.__version__, np.show_config

In [2]:
import numpy as np

#### 2. Raqamli qiymatlar ro'yxatini bir o'lchovli NumPy massiviga aylantiring! 

`💡Ishora` numpy.array

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])

#### 3. Qiymatlari noldan iborat bo'lgan to'qqiz o'lchovli massiv yarating.



In [ ]:
zero = np.zeros(shape=(9,9))
zero

array([[0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.],
       [0., 0., 0., 0., 0., 0., 0., 0., 0.]])

`💡Ishora` np.zeros

#### 4. Massiv yarating va uning xotira hajmini toping.



`💡Ishora` size, itemsize

In [ ]:
arr = np.array([1,2,3,4,5,6,7,8,9])
arr.size

9

#### 5. NumPy kutubxonasidagi add funksiyasi hujjatlarini buyruq satridan qanday olishi mumkin? 


`💡Ishora` np.info

In [ ]:
info = np.info(arr)

class:  ndarray
shape:  (9,)
strides:  (8,)
itemsize:  8
aligned:  True
contiguous:  True
fortran:  True
data pointer: 0x26a40f0
byteorder:  little
byteswap:  False
type: int64


#### 6. Shunday vekor yaratingki u o'n ikki o'lchamda va qiymatlari noldan iborat bo'lsin, lekin vektorning oltinchi qiymati 1 ga teng bo'lsin.



`💡Ishora` array[12]

In [ ]:
vektor = np.array([0,0,0,0,0,0,0,0,0,0,0,0]) 
vektor[5] = 1
vektor

array([0, 0, 0, 0, 0, 1, 0, 0, 0, 0, 0, 0])

#### 7. Qiymatlari 20 dan 59 gacha bo'lgan vektor yarating.



`💡Ishora` arange

In [ ]:
arr1 = np.arange(20, 60, 1)
arr1

array([20, 21, 22, 23, 24, 25, 26, 27, 28, 29, 30, 31, 32, 33, 34, 35, 36,
       37, 38, 39, 40, 41, 42, 43, 44, 45, 46, 47, 48, 49, 50, 51, 52, 53,
       54, 55, 56, 57, 58, 59])

#### 8. Vektor yarating va uni teskari o'zgartiring 
(birinchi element oxirgisi bo'lsin)



`💡Ishora` array[::-1]

In [ ]:
arr = np.arange(0, 20, 2)
arr = arr[::-1]
arr

array([18, 16, 14, 12, 10,  8,  6,  4,  2,  0])

#### 9. 12 dan 20 gacha bo'lgan qiymatlarga ega 3x3 matritsa yarating.


`💡Ishora` reshape

In [ ]:
arr1 = np.arange(12, 21, 1).reshape(3, 3)
arr1

array([[12, 13, 14],
       [15, 16, 17],
       [18, 19, 20]])

#### 10. Quyidagi matritsadan foydalanib nolga teng bo'lmagan elementlarning indekslarini toping.
[3, 7, 0, 0, 9, 0] 





`💡Ishora` np.nonzero

In [ ]:
np.nonzero([3, 7, 0, 0, 9, 0])

(array([0, 1, 4]),)

#### 11. Tasodifiy qiymatlar bilan 2x2x2 o'lchovidagi massiv yarating.


`💡Ishora` np.random.random

In [ ]:
arr2 = np.random.randint(10, size=(2, 2, 2))
arr2

array([[[9, 6],
        [8, 0]],

       [[9, 1],
        [2, 4]]])

#### 12. Tasodifiy sonlardan tashkil topgan 9X9 o'lchamidagi massiv yarating. So'ng uning eng katta va eng kichik qiymatlarini toping


`💡Ishora` min, max

In [ ]:
arr3 = np.random.randint(30, size=(9, 9))
arr3.max()
arr3.min()

0

#### 13. Quyidagi misol qanday natija beradi?


```python
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1
```


`💡Ishora` NaN = not a number, inf = infinity

In [ ]:
0 * np.nan
np.nan == np.nan
np.inf > np.nan
np.nan - np.nan
np.nan in set([np.nan])
0.7 == 7 * 0.1

False

#### 14. O'lchamlari 6x3 va 3x4 bo'lgan martitsa yarating, so'ng ularning  ko'paytmasini hisoblang.



`💡Ishora` np.dot` or `np.ones

In [ ]:
mat = np.random.randint(20, size=(6, 3))
mat2 = np.arange(1, 13, 1).reshape(3, 4)
result = np.dot(mat, mat2)
result

array([[ 29,  42,  55,  68],
       [ 67,  78,  89, 100],
       [ 56,  80, 104, 128],
       [135, 174, 213, 252],
       [199, 230, 261, 292],
       [161, 194, 227, 260]])

#### 15. Quyidagi misol qanday natija beradi?

```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))


10
10


#### 16. NumPy kutubxonasi yordamida ikkita massivni solishtiring va ular usida quyidagi amallarni bajaring.

```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])
a>b
a>=b
a<b
a<=b

array([ True,  True])

#### 17. Quyidagi misol qanday natija beradi?

```python
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)
```

In [ ]:
np.array(0) / np.array(0)
np.array(0) // np.array(0)
np.array([np.nan]).astype(int).astype(float)

<ipython-input-53-cd809174da5d>:1: RuntimeWarning: invalid value encountered in true_divide
  np.array(0) / np.array(0)
<ipython-input-53-cd809174da5d>:2: RuntimeWarning: divide by zero encountered in floor_divide
  np.array(0) // np.array(0)


array([-9.22337204e+18])

#### 18. Ikkita massiv yarating va ular orasidagi umumiy qiymatlarni toping


`💡Ishora` np.intersect1d

In [ ]:
arr1 = np.random.randint(10, size=(1, 10))
arr2 = np.random.randint(10, size=(1, 10))
print(arr1)
print(arr2)
np.intersect1d(arr1, arr2)

[[3 1 3 5 0 4 7 5 7 4]]
[[9 7 9 9 0 2 7 7 5 9]]


array([0, 5, 7])

#### 19. Tasodifiy sonlardan iborat bo'lgan massiv yarating, so'ng ularni quyida berilgan 4 xil usul yordamida musbat sonlarning butun qismini ajratib oling.

`💡Ishora` %, np.floor, astype, np.trunc

In [ ]:
son = np.random.randn(1,10)
np.floor(son)
son.astype
np.trunc(son)

array([[ 0.,  1., -0., -0., -0.,  0.,  0.,  1., -0.,  1.]])

#### 20. O'lchovlari 3x3 matritsa yarating, ularning qator qiymatlari 0 dan 2 gacha bo'lsin.



`💡Ishora` np.arange

In [ ]:
son1 = np.random.randint(3, size=(3, 3))
son1

#### 21. O'chamlari 10 bo'lgan tasodifiy vektor yarating va uni o'sish tartibida chiqaruvchi dastur tuzing.



`💡Ishora` sort

In [ ]:
vektor = np.random.randint(25, size=(5, 5))
np.sort(vektor)

array([[ 3,  5,  9, 20, 22],
       [ 5,  9, 20, 20, 21],
       [ 5,  9,  9, 18, 24],
       [ 1,  9, 19, 21, 23],
       [ 5,  8, 10, 17, 23]])

#### 22. A va B nomi bilan ikkita tasodifiy qiymatlardan iborat bo'lgan massiv yarating, so'ng ulardan qaysi biri katta yoki kichik ekanligini tekshiring.

`💡Ishora` np.allclose, np.array_equal

In [ ]:
A = np.array([1,3,5])
B = np.array([2,1,6])
np.array_equal(A, B)

False

#### 23. O'lchamlari 6x3 va 3x4 matritsa tuzing va ularni o'zaro ko'paytiring. 


`💡Ishora` np.dot or np.ones

In [ ]:
son1 = np.random.randint(2, size=(5, 5))
son2 = np.arange(1, 26, 1).reshape(5, 5)
print(son1)
print(son2)
np.dot(son1, son2)

[[1 1 0 0 0]
 [0 1 1 1 0]
 [0 0 1 1 0]
 [0 0 0 0 1]
 [1 1 0 0 1]]
[[ 1  2  3  4  5]
 [ 6  7  8  9 10]
 [11 12 13 14 15]
 [16 17 18 19 20]
 [21 22 23 24 25]]


array([[ 7,  9, 11, 13, 15],
       [33, 36, 39, 42, 45],
       [27, 29, 31, 33, 35],
       [21, 22, 23, 24, 25],
       [28, 31, 34, 37, 40]])

#### 24. Tasodifiy sonlardan iborat bo'lgan o'lchami 5 ga teng vektor yarating, so'ng uning eng katta qiymatini 0 ga o'zgartiring.


`💡Ishora` argmax

In [ ]:
arr = np.array([12, 32, 5, 3, 43])
arr[np.argmax(arr)] = 0
arr

array([12, 32,  5,  3,  0])

#### 25. Quyidagi dastur qanday natija beradi?
```python
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))
```

In [ ]:
print(sum(range(5),-1))
from numpy import *
print(sum(range(5),-1))

10
10


#### 26. NumPy kutubxonasi yordamida ikkita massivni solishtiruvchi dastur tuzing.
```python
Array a: [1 2]
Array b: [4 5]
a > b 
[False False]
a >= b 
[False False] 
a < b 
[ True True] 
a <= b 
[ True True]
```

In [ ]:
a = np.array([1, 2])
b = np.array([4, 5])
a >= b
a > b
a < b
a <= b

array([ True,  True])

#### 27. Ikkita umumiy qiymatlari mavjud bo'lgan massiv yarating, so'ng ulardagi umumiy qiymatlarni aniqlovchi dastur tuzing.


`💡Ishora` np.intersect1d

In [ ]:
arr1 = np.random.randint(20, size=(1, 10))
arr2 = np.random.randint(20, size=(1, 10))
print(arr1)
print(arr2)
np.intersect1d(arr1, arr2)

[[ 7  7 13  8  9  4  7 12  3 16]]
[[ 7 10  5 13 10 15 19  1 11 11]]


array([ 7, 13])

#### 28. NumPy kutubxonasi yordamida kecha, bugun va ertangi kun sanalarini aniqlang.


`💡Ishora` np.datetime64, np.timedelta64

In [ ]:
arr = np.datetime64('2023-01-26')
arr

numpy.datetime64('2023-01-26')

#### 29. 2016 yil yanvar oyiga to'g'ri keladigan barcha sanalarni NumPy kutubxonasi yordamida aniqlang.


`💡Ishora` np.arange(dtype=datetime64['D'])

In [9]:
arr = np.arange('2016-01', '2016-02', dtype='datetime64[D]')
arr

array(['2016-01-01', '2016-01-02', '2016-01-03', '2016-01-04',
       '2016-01-05', '2016-01-06', '2016-01-07', '2016-01-08',
       '2016-01-09', '2016-01-10', '2016-01-11', '2016-01-12',
       '2016-01-13', '2016-01-14', '2016-01-15', '2016-01-16',
       '2016-01-17', '2016-01-18', '2016-01-19', '2016-01-20',
       '2016-01-21', '2016-01-22', '2016-01-23', '2016-01-24',
       '2016-01-25', '2016-01-26', '2016-01-27', '2016-01-28',
       '2016-01-29', '2016-01-30', '2016-01-31'], dtype='datetime64[D]')

#### 30. 4 xil usul yordamida musbat sonlarning tasodifiy massivining butun son qismini ajratib oling.


`💡Ishora` %, np.floor, astype, np.trunc`

In [22]:
arr1 = np.array([12, 3.5, 2.1, 5.8, 7])
arr1 -= arr1%1
arr1
np.floor(arr1)
np.trunc(arr1)

array([12.,  3.,  2.,  5.,  7.])

#### 31. Qator qiymatlari 0 dan 2 gacha bo'lgan 3x3 matritsa yarating.


`💡Ishora` np.arange

In [27]:
matrix = np.arange(0, 2, 1)
matrix

array([0, 3])

#### 32. Tasodifiy qiymatlardan tashkil topgan 10 o'lchovli vektor yarating, so'ng uning qiymatlarini o'sish tartibida yozing.


`💡Ishora` sort

In [32]:
vek = np.random.randint(10, size=(1, 10))
np.sort(vek)

array([[0, 1, 1, 1, 3, 4, 6, 9, 9, 9]])

#### 33. Ixtiyoriy kichik massivlar yarating, ular yeg'indisini np.sum funksiyasidanda tezroq hisoblovchi dastur tuzing.


`💡Ishora` np.add.reduce

In [40]:
arr1 = np.array([1,2,3])
arr2 = np.array([1,2,3])
arr3 = np.array([7,8,9])
%time np.sum(arr1)
%time np.add.reduce(arr2)

CPU times: user 108 µs, sys: 0 ns, total: 108 µs
Wall time: 114 µs
CPU times: user 56 µs, sys: 0 ns, total: 56 µs
Wall time: 59.8 µs


6

#### 34. Tasodifiy qiymatlardan tashkil topgan 5 o'lchovli vektor yarating, so'ng uning eng katta qiymatini 0 raqamiga almashtiring.


`💡Ishora` argmax

In [44]:
arr1 = np.array([34, 3, 456, 7, 545, 3000, 890])
arr1[np.argmax(arr1)] = 0
arr1

array([ 34,   3, 456,   7, 545,   0, 890])

#### 35. [1, 2, 3, 4, 5] vektor berilgan, har bir qiymat orasiga ketma-ket 3 ta nol raqamini yozuvchi dastur tuzing.


`💡Ishora` array[::4]

In [55]:
arr = np.array([1, 2, 3, 4, 5])
arr0 = np.array([0, 0, 0])
arr[::1].add(arr0)
arr

AttributeError: ignored

#### 36. Quyidagi a massiv berilgan, a = [1,2,3,4,5,6,7,8,9,10,11,12,13,14] undan foydalangan holda siz quyidagi b massivni yarata olasizmi, b = [[1,2,3,4], [2,3,4,5], [3,4,5,6], ..., [11,12,13,14]]? 


`💡Ishora` stride_tricks.as_strided

In [72]:
from numpy.lib import stride_tricks
a = np.asarray(range(1, 30), np.int8)
b = stride_tricks.as_strided(a, shape=(11,4), strides=(1,1))
b

array([[ 1,  2,  3,  4],
       [ 2,  3,  4,  5],
       [ 3,  4,  5,  6],
       [ 4,  5,  6,  7],
       [ 5,  6,  7,  8],
       [ 6,  7,  8,  9],
       [ 7,  8,  9, 10],
       [ 8,  9, 10, 11],
       [ 9, 10, 11, 12],
       [10, 11, 12, 13],
       [11, 12, 13, 14]], dtype=int8)

#### 37. Ixtiyoriy sonlardan tashkil topgan massiv yarating, unga o'xshash qiymatlar kiriting. So'ng, o'xshash qiymatlarni topuvchi dastur tuzing.


`💡Ishora` np.bincount, argmax

In [81]:
array2 = [10, 11, 4, 6, 2, 1, 9]
array1 = [1, 3, 1, 3, 1, 2, 2]
  
bin = np.bincount(array1, array2)
bin

array([ 0., 16., 10., 17.])

#### BONUS!

`💡O'zingiz javob berishni istagan savolni kiriting va unga javob bering!`

In [83]:
x = np.asarray(range(1,13), np.int32).reshape(3,2,2)
print(x)
stride_tricks.as_strided(x, shape=(3,2,2), strides=(16,4,8))

[[[ 1  2]
  [ 3  4]]

 [[ 5  6]
  [ 7  8]]

 [[ 9 10]
  [11 12]]]


array([[[ 1,  3],
        [ 2,  4]],

       [[ 5,  7],
        [ 6,  8]],

       [[ 9, 11],
        [10, 12]]], dtype=int32)