<a href="https://colab.research.google.com/github/Shohjahon02/first_my_git/blob/main/ML1_2_level.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import pandas as pd
import numpy as np
import sklearn # scikit-learn kutubxonasi

In [2]:
df = pd.read_csv('/content/uy_data1.csv', index_col=0)
df

location           district  \
0     город Ташкент, Юнусабадский район, Юнусабад 8-...       Юнусабадский   
1     город Ташкент, Яккасарайский район, 1-й тупик ...      Яккасарайский   
2     город Ташкент, Чиланзарский район, Чиланзар 2-...       Чиланзарский   
3     город Ташкент, Чиланзарский район, Чиланзар 9-...       Чиланзарский   
4     город Ташкент, Чиланзарский район, площадь Актепа       Чиланзарский   
...                                                 ...                ...   
7561  город Ташкент, Яшнободский район, 1-й проезд А...        Яшнободский   
7562  город Ташкент, Шайхантахурский район, Зульфиях...    Шайхантахурский   
7563  город Ташкент, Мирзо-Улугбекский район, Буюк И...  Мирзо-Улугбекский   
7564  город Ташкент, Чиланзарский район, Чиланзар 6-...       Чиланзарский   
4089                                                NaN                NaN   

      rooms  size  level  max_levels     price  
0       3.0  57.0    4.0         4.0   52000.0  
1       2.0  52.0    4.0         5.0   56000.0  
2       2.0  42.0    4.0         4.0   37000.0  
3       3.0  65.0    1.0         4.0   49500.0  
4       3.0  70.0    3.0         5.0   55000.0  
...     ...   ...    ...         ...       ...  
7561    2.0  49.0    1.0         4.0   32000.0  
7562    2.0  64.0    3.0         9.0   40000.0  
7563    1.0  18.0    1.0         4.0   11000.0  
7564    1.0  30.0    2.0         4.0   22914.0  
4089    NaN   NaN    NaN         NaN  118000.0  

[7410 rows x 7 columns]

In [3]:
df.drop(4089, inplace=True)

In [4]:
df

location           district  \
0     город Ташкент, Юнусабадский район, Юнусабад 8-...       Юнусабадский   
1     город Ташкент, Яккасарайский район, 1-й тупик ...      Яккасарайский   
2     город Ташкент, Чиланзарский район, Чиланзар 2-...       Чиланзарский   
3     город Ташкент, Чиланзарский район, Чиланзар 9-...       Чиланзарский   
4     город Ташкент, Чиланзарский район, площадь Актепа       Чиланзарский   
...                                                 ...                ...   
7560  город Ташкент, Яшнободский район, Городок Авиа...        Яшнободский   
7561  город Ташкент, Яшнободский район, 1-й проезд А...        Яшнободский   
7562  город Ташкент, Шайхантахурский район, Зульфиях...    Шайхантахурский   
7563  город Ташкент, Мирзо-Улугбекский район, Буюк И...  Мирзо-Улугбекский   
7564  город Ташкент, Чиланзарский район, Чиланзар 6-...       Чиланзарский   

      rooms  size  level  max_levels    price  
0       3.0  57.0    4.0         4.0  52000.0  
1       2.0  52.0    4.0         5.0  56000.0  
2       2.0  42.0    4.0         4.0  37000.0  
3       3.0  65.0    1.0         4.0  49500.0  
4       3.0  70.0    3.0         5.0  55000.0  
...     ...   ...    ...         ...      ...  
7560    1.0  38.0    5.0         5.0  24500.0  
7561    2.0  49.0    1.0         4.0  32000.0  
7562    2.0  64.0    3.0         9.0  40000.0  
7563    1.0  18.0    1.0         4.0  11000.0  
7564    1.0  30.0    2.0         4.0  22914.0  

[7409 rows x 7 columns]

In [5]:
from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

In [6]:
housing = train_set.drop('price', axis=1)
housing_labels = train_set['price'].copy()

In [7]:
housing

location           district  \
5740      город Ташкент, Учтепинский район, Чиланзар-13        Учтепинский   
5354        город Ташкент, Яккасарайский район, Кушбеги      Яккасарайский   
1073  город Ташкент, Юнусабадский район, Юнусабад 4-...       Юнусабадский   
638   город Ташкент, Мирзо-Улугбекский район, Мирзо-...  Мирзо-Улугбекский   
2056    город Ташкент, Яккасарайский район, Ул Нукуская      Яккасарайский   
...                                                 ...                ...   
5299  город Ташкент, Учтепинский район, Чиланзар 14-...        Учтепинский   
5334            город Ташкент, Мирабадский район, Нукус        Мирабадский   
5500  город Ташкент, Сергелийский район, 1-й проезд ...       Сергелийский   
876        город Ташкент, Чиланзарский район, Чопан ота       Чиланзарский   
7424    город Ташкент, Мирзо-Улугбекский район, Ялангач  Мирзо-Улугбекский   

      rooms   size  level  max_levels  
5740    2.0   56.0    3.0         5.0  
5354    2.0   64.0    1.0         5.0  
1073    4.0   80.0    3.0         4.0  
638     4.0   80.0    5.0         5.0  
2056    1.0   43.0    5.0        16.0  
...     ...    ...    ...         ...  
5299    3.0   65.0    1.0         4.0  
5334    4.0  121.0    9.0        10.0  
5500    2.0   41.0    4.0         7.0  
876     2.0   56.0    4.0         4.0  
7424    2.0   46.0    3.0         4.0  

[5927 rows x 6 columns]

In [8]:
housing_labels

5740    33000.0
5354    42000.0
1073    77500.0
638     47000.0
2056    38500.0
         ...   
5299    46900.0
5334    99000.0
5500    32000.0
876     35000.0
7424    33500.0
Name: price, Length: 5927, dtype: float64

In [9]:
housing.isnull().sum()

location      0
district      0
rooms         0
size          0
level         0
max_levels    0
dtype: int64

In [10]:
housing_loc = housing[['location']]
housing_dist = housing[['district']]

In [11]:
housing_dist

district
5740        Учтепинский
5354      Яккасарайский
1073       Юнусабадский
638   Мирзо-Улугбекский
2056      Яккасарайский
...                 ...
5299        Учтепинский
5334        Мирабадский
5500       Сергелийский
876        Чиланзарский
7424  Мирзо-Улугбекский

[5927 rows x 1 columns]

In [15]:
from sklearn.preprocessing import OrdinalEncoder
ordinal_encoder = OrdinalEncoder()
housing_loc_encoded = ordinal_encoder.fit_transform(housing_loc)
housing_loc_encoded[:10]

array([[ 618.],
       [1125.],
       [1044.],
       [ 273.],
       [1164.],
       [ 575.],
       [ 783.],
       [ 747.],
       [ 600.],
       [1337.]])

In [13]:
ordinal_encoder.categories_

[array(['город Ташкент, Бектемирский район, Конечная остановка',
        'город Ташкент, Бектемирский район, Корзинка',
        'город Ташкент, Бектемирский район, Массив Водник', ...,
        'город Ташкент, Яшнободский район, пр-т Мирзо Улугбека',
        'город Ташкент, Яшнободский район, тупик Мавляна Риёзи',
        'город Ташкент, Яшнободский район, ул Садик Азимова'], dtype=object)]

In [16]:
from sklearn.preprocessing import OneHotEncoder
cat_encoder = OneHotEncoder()
housing_dist_1hot = cat_encoder.fit_transform(housing_dist)
housing_dist_1hot.toarray()

array([[0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 1., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       ...,
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 0., ..., 0., 0., 0.],
       [0., 0., 1., ..., 0., 0., 0.]])

In [21]:
housing_num = housing.drop(['location', 'district'], axis=1)
housing_num['location'] = housing_loc_encoded
housing_num

rooms   size  level  max_levels  location
5740    2.0   56.0    3.0         5.0     618.0
5354    2.0   64.0    1.0         5.0    1125.0
1073    4.0   80.0    3.0         4.0    1044.0
638     4.0   80.0    5.0         5.0     273.0
2056    1.0   43.0    5.0        16.0    1164.0
...     ...    ...    ...         ...       ...
5299    3.0   65.0    1.0         4.0     603.0
5334    4.0  121.0    9.0        10.0      84.0
5500    2.0   41.0    4.0         7.0     485.0
876     2.0   56.0    4.0         4.0     813.0
7424    2.0   46.0    3.0         4.0     374.0

[5927 rows x 5 columns]

In [ ]:
housing_num.append(housing_dist_1hot.toarray())
housing_num

In [25]:
from sklearn.preprocessing import MinMaxScaler
min_mix_scaler = MinMaxScaler()

min_mix_scaler.fit_transform(housing_num)

array([[0.11111111, 0.09090909, 0.11111111, 0.16666667, 0.44945455],
       [0.11111111, 0.10909091, 0.        , 0.16666667, 0.81818182],
       [0.33333333, 0.14545455, 0.11111111, 0.125     , 0.75927273],
       ...,
       [0.11111111, 0.05681818, 0.16666667, 0.25      , 0.35272727],
       [0.11111111, 0.09090909, 0.16666667, 0.125     , 0.59127273],
       [0.11111111, 0.06818182, 0.11111111, 0.125     , 0.272     ]])

In [26]:
from sklearn.preprocessing import StandardScaler
standart_scaler = StandardScaler()
standart_scaler.fit_transform(housing_num)

array([[-0.58484987, -0.47590298, -0.31358452, -0.40095879, -0.13874456],
       [-0.58484987, -0.25140092, -1.20714963, -0.40095879,  1.25171745],
       [ 1.30368469,  0.19760319, -0.31358452, -0.78150046,  1.02957264],
       ...,
       [-0.58484987, -0.89684434,  0.13319804,  0.36012456, -0.50350086],
       [-0.58484987, -0.47590298,  0.13319804, -0.78150046,  0.39604853],
       [-0.58484987, -0.75653056, -0.31358452, -0.78150046, -0.80792154]])

In [27]:
housing

location           district  \
5740      город Ташкент, Учтепинский район, Чиланзар-13        Учтепинский   
5354        город Ташкент, Яккасарайский район, Кушбеги      Яккасарайский   
1073  город Ташкент, Юнусабадский район, Юнусабад 4-...       Юнусабадский   
638   город Ташкент, Мирзо-Улугбекский район, Мирзо-...  Мирзо-Улугбекский   
2056    город Ташкент, Яккасарайский район, Ул Нукуская      Яккасарайский   
...                                                 ...                ...   
5299  город Ташкент, Учтепинский район, Чиланзар 14-...        Учтепинский   
5334            город Ташкент, Мирабадский район, Нукус        Мирабадский   
5500  город Ташкент, Сергелийский район, 1-й проезд ...       Сергелийский   
876        город Ташкент, Чиланзарский район, Чопан ота       Чиланзарский   
7424    город Ташкент, Мирзо-Улугбекский район, Ялангач  Мирзо-Улугбекский   

      rooms   size  level  max_levels  
5740    2.0   56.0    3.0         5.0  
5354    2.0   64.0    1.0         5.0  
1073    4.0   80.0    3.0         4.0  
638     4.0   80.0    5.0         5.0  
2056    1.0   43.0    5.0        16.0  
...     ...    ...    ...         ...  
5299    3.0   65.0    1.0         4.0  
5334    4.0  121.0    9.0        10.0  
5500    2.0   41.0    4.0         7.0  
876     2.0   56.0    4.0         4.0  
7424    2.0   46.0    3.0         4.0  

[5927 rows x 6 columns]

In [29]:
housing_onehot = pd.get_dummies(housing['district'])
housing_onehot

Бектемирский  Мирабадский  Мирзо-Улугбекский  Олмазорский  Сергелийский  \
5740             0            0                  0            0             0   
5354             0            0                  0            0             0   
1073             0            0                  0            0             0   
638              0            0                  1            0             0   
2056             0            0                  0            0             0   
...            ...          ...                ...          ...           ...   
5299             0            0                  0            0             0   
5334             0            1                  0            0             0   
5500             0            0                  0            0             1   
876              0            0                  0            0             0   
7424             0            0                  1            0             0   

      Учтепинский  Чиланзарский  Шайхантахурский  Юнусабадский  Яккасарайский  \
5740            1             0                0             0              0   
5354            0             0                0             0              1   
1073            0             0                0             1              0   
638             0             0                0             0              0   
2056            0             0                0             0              1   
...           ...           ...              ...           ...            ...   
5299            1             0                0             0              0   
5334            0             0                0             0              0   
5500            0             0                0             0              0   
876             0             1                0             0              0   
7424            0             0                0             0              0   

      Янгихаётский  Яшнободский  
5740             0            0  
5354             0            0  
1073             0            0  
638              0            0  
2056             0            0  
...            ...          ...  
5299             0            0  
5334             0            0  
5500             0            0  
876              0            0  
7424             0            0  

[5927 rows x 12 columns]

In [32]:
housing_num.head()

rooms  size  level  max_levels  location
5740    2.0  56.0    3.0         5.0     618.0
5354    2.0  64.0    1.0         5.0    1125.0
1073    4.0  80.0    3.0         4.0    1044.0
638     4.0  80.0    5.0         5.0     273.0
2056    1.0  43.0    5.0        16.0    1164.0