<a href="https://colab.research.google.com/github/Shohjahon02/first_my_git/blob/main/ML_1_4_full.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [25]:
import pandas as pd
import numpy as np
import sklearn # scikit-learn kutubxonasi

df = pd.read_csv('/content/uy_data1.csv', index_col=0)
df.drop(['location'], axis=1, inplace=True)

from sklearn.model_selection import train_test_split
train_set, test_set = train_test_split(df, test_size=0.2, random_state=42)

X_train = train_set.drop("price", axis=1)
y = train_set["price"].copy()

housing_num = X_train.drop(['district'], axis=1)

In [4]:
from sklearn.pipeline import Pipeline
from sklearn.impute import SimpleImputer
from sklearn.preprocessing import OneHotEncoder, StandardScaler

num_pipeline = Pipeline([
          ('std_scaler', StandardScaler())             
])

In [26]:
from sklearn.compose import ColumnTransformer

num_attribs = list(housing_num)
dist_attribs = ['district']

full_pipeline = ColumnTransformer([
    ('num', num_pipeline, num_attribs),
    ('dist', OneHotEncoder(), dist_attribs)
])

In [27]:
X_prepared = full_pipeline.fit_transform(X_train)

In [28]:
X_prepared[0:5,:]

array([[ 2.2481754 ,  1.00669977, -0.31445736, -0.40179114,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ],
       [-0.58478367, -0.36105029,  0.13224842, -0.40179114,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         1.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.30385571,  0.19721504, -0.31445736, -0.78343156,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  1.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.30385571,  0.19721504,  0.5789542 , -0.40179114,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-1.52910336, -0.83557582,  0

In [29]:
from sklearn.linear_model import LinearRegression

LR_model = LinearRegression()

In [30]:
LR_model.fit(X_prepared, y)

LinearRegression()

In [31]:
# tasodifiy 5 ta qatorni ajratib olamiz
test_data = X_train.sample(5)
test_data

district  rooms   size  level  max_levels
626   Мирзо-Улугбекский    2.0   50.0    5.0         5.0
7559    Шайхантахурский    1.0   27.5    2.0         4.0
7523       Сергелийский    4.0  100.0    2.0         9.0
3049  Мирзо-Улугбекский    4.0   96.0    4.0         4.0
1832        Учтепинский    2.0   56.0    6.0         6.0

In [32]:
# yuqoridagi qatorlarga mos keluvchi narxlarni ajratib olamiz (biz aynan shu qiymatlarni bashorat qilishimiz kerak)
test_label = y.loc[test_data.index]
test_label

626     35000.0
7559    23000.0
7523    38000.0
3049    83000.0
1832    37500.0
Name: price, dtype: float64

In [33]:
test_data_prepared = full_pipeline.transform(test_data)
test_data_prepared

array([[-0.58478367, -0.64018295,  0.5789542 , -0.40179114,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-1.52910336, -1.26823145, -0.76116314, -0.78343156,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.30385571,  0.75548037, -0.76116314,  1.12477055,  0.        ,
         0.        ,  0.        ,  0.        ,  1.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [ 1.30385571,  0.64382731,  0.13224842, -0.78343156,  0.        ,
         0.        ,  1.        ,  0.        ,  0.        ,  0.        ,
         0.        ,  0.        ,  0.        ,  0.        ,  0.        ,
         0.        ],
       [-0.58478367, -0.47270335,  1

In [34]:
predicted_data = LR_model.predict(test_data_prepared)
predicted_data

array([35515.6580435 , 18976.10143278, 67599.25199983, 74371.21851724,
       33002.78211992])

In [35]:
pd.DataFrame({'Prognoz':predicted_data, 'Real baxosi': test_label})

Prognoz  Real baxosi
626   35515.658044      35000.0
7559  18976.101433      23000.0
7523  67599.252000      38000.0
3049  74371.218517      83000.0
1832  33002.782120      37500.0

In [60]:
test_set.dropna(inplace=True)

In [61]:
test_set

district  rooms   size  level  max_levels    price
5133      Яккасарайский    2.0   53.0    4.0         5.0  52000.0
1571       Сергелийский    2.0   49.0    3.0         7.0  35000.0
2472      Яккасарайский    2.0   60.0    2.0         3.0  60000.0
5859  Мирзо-Улугбекский    3.0   75.0    5.0         9.0  41500.0
2592  Мирзо-Улугбекский    2.0   60.0    2.0         9.0  61000.0
...                 ...    ...    ...    ...         ...      ...
1513       Юнусабадский    2.0   53.0    3.0         4.0  34500.0
1622        Олмазорский    3.0  113.0    4.0         4.0  63000.0
4083       Юнусабадский    2.0   58.0    2.0         4.0  41500.0
6068        Мирабадский    2.0   40.0    1.0         1.0  26000.0
4487       Юнусабадский    2.0   57.0    6.0         9.0  68000.0

[1481 rows x 6 columns]

In [62]:
X_test = test_set.drop('price', axis=1)
X_test

district  rooms   size  level  max_levels
5133      Яккасарайский    2.0   53.0    4.0         5.0
1571       Сергелийский    2.0   49.0    3.0         7.0
2472      Яккасарайский    2.0   60.0    2.0         3.0
5859  Мирзо-Улугбекский    3.0   75.0    5.0         9.0
2592  Мирзо-Улугбекский    2.0   60.0    2.0         9.0
...                 ...    ...    ...    ...         ...
1513       Юнусабадский    2.0   53.0    3.0         4.0
1622        Олмазорский    3.0  113.0    4.0         4.0
4083       Юнусабадский    2.0   58.0    2.0         4.0
6068        Мирабадский    2.0   40.0    1.0         1.0
4487       Юнусабадский    2.0   57.0    6.0         9.0

[1481 rows x 5 columns]

In [63]:
y_test = test_set['price'].copy()
y_test

5133    52000.0
1571    35000.0
2472    60000.0
5859    41500.0
2592    61000.0
         ...   
1513    34500.0
1622    63000.0
4083    41500.0
6068    26000.0
4487    68000.0
Name: price, Length: 1481, dtype: float64

In [49]:
y_test.isnull().sum()

0

Series([], Name: price, dtype: float64)

In [42]:
X_test.dropna(inplace=True)

In [43]:
X_test.isnull().sum()

district      0
rooms         0
size          0
level         0
max_levels    0
dtype: int64

In [71]:
X_test_prepared = full_pipeline.transform(X_test)

In [72]:
y_predicted = LR_model.predict(X_test_prepared)

In [73]:
from sklearn.metrics import mean_squared_error
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

22907.173155789344


In [67]:
from sklearn.tree import DecisionTreeRegressor
Tree_model = DecisionTreeRegressor()
Tree_model.fit(X_prepared, y)

DecisionTreeRegressor()

In [68]:
y_predicted = Tree_model.predict(X_test_prepared)

In [69]:
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

25225.429128110205


In [74]:
from sklearn.ensemble import RandomForestRegressor
RF_model = RandomForestRegressor()
RF_model.fit(X_prepared, y)

RandomForestRegressor()

In [75]:
y_predicted = RF_model.predict(X_test_prepared)
lin_mse = mean_squared_error(y_test, y_predicted)
# RMSE hisoblaymiz
lin_rmse = np.sqrt(lin_mse)
print(lin_rmse)

19636.59951196104


In [81]:
df.isnull().sum()

district      0
rooms         0
size          0
level         0
max_levels    0
price         0
dtype: int64

In [80]:
df.dropna(inplace=True)

In [82]:
X = df.drop("price", axis=1)
y = df["price"].copy()

X_prepared = full_pipeline.transform(X)

In [83]:
def display_scores(scores):
    print("Scores:", scores)
    print("Mean:", scores.mean())
    print("Std.dev:", scores.std())

In [84]:
from sklearn.model_selection import cross_val_score

In [85]:
scores = cross_val_score(LR_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)

In [86]:
display_scores(LR_rmse_scores)

Scores: [20892.24491137 17623.29337287 27677.05800605 26739.73137187
 26018.71476563 29307.30090143 24398.58728157 24929.44271547
 22215.44649957 16320.26753202]
Mean: 23612.208735786262
Std.dev: 4065.3647037453516


In [87]:
scores = cross_val_score(Tree_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [21664.03382503 23638.34227447 30273.767781   28183.49112344
 27690.48932462 26600.59383175 26470.42351776 26984.03291444
 25944.53773563 16405.86950313]
Mean: 25385.558183126726
Std.dev: 3742.9115562059105


In [88]:
scores = cross_val_score(RF_model, X_prepared, y, scoring="neg_mean_squared_error", cv=10)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [16398.13627425 16341.58183639 23091.37074562 23936.45615841
 22193.38390535 22954.5060067  20596.21175445 22734.41914568
 19422.81458387 13629.21266573]
Mean: 20129.809307644395
Std.dev: 3369.4781621572083


In [89]:
import pickle

filename = 'RF_model.pkl' # faylga istalgan nom beramiz
with open(filename, 'wb') as file:
    pickle.dump(RF_model, file)

In [90]:
with open(filename, 'rb') as file:
    model = pickle.load(file)

In [91]:
scores = cross_val_score(model, X_prepared, y, scoring="neg_mean_squared_error", cv=5)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [16876.85488387 23773.44126997 22492.13127933 21933.76674394
 17299.50310833]
Mean: 20475.139457087134
Std.dev: 2832.206295848962


In [92]:
import joblib

filename = 'RF_model.jbl' # faylga istalgan nom beramiz
joblib.dump(RF_model, filename)

['RF_model.jbl']

In [93]:
model = joblib.load(filename)

In [94]:
scores = cross_val_score(model, X_prepared, y, scoring="neg_mean_squared_error", cv=5)
LR_rmse_scores = np.sqrt(-scores)
display_scores(LR_rmse_scores)

Scores: [16561.51187847 23913.32933996 22758.79093093 21794.5570042
 16866.68176764]
Mean: 20378.97418424089
Std.dev: 3068.1683562152184


In [95]:
filename = 'pipeline.jbl'
joblib.dump(full_pipeline, filename)

['pipeline.jbl']